### ISSUE TITLE
Cannot run production build; Uncaught Syntax Error: Unexpected String

### ISSUE THREAD

**Issue by LucasMW** [mbasso/asm-dom-boilerplate#9] opened 2018-10-25 14:20 UTC
make doesn't work.
I cannot run the generated production build. (dist directory)
npm start works normally, however.

Picture of the error:

<img width="279" alt="captura de tela 2018-10-25 as 11 07 06" src="https://user-images.githubusercontent.com/8429832/47506508-968e0400-d846-11e8-812d-6d14e38316fd.png">

My environment:
Mac OS 10.13
node v10.9.0
npm v6.2.0
GNU Make v3.81
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.11
clang version 6.0.1  (emscripten 1.38.10 : 1.38.10)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: (...)/emsdk/clang/e1.38.10_64bit
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.38.11, 1.38.10, 1.38.10)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)

**Steps to reproduce**

just run make on my environment, I guess.

**Versions**

- asm-dom: cloned yesterday
- Browser: tried on both Google Chrome  70.0.3538.67 and Brave  0.25.2

**Comment by mbasso** [comment] 2018-10-26 12:47
Hi @LucasMW,
thank you for opening this issue, I've tried but I'm unable to reproduce it. Can you please give me the detailed list of actions that you've done?
The following works for me:

```bash
npm install
make
node dist/server.js
```

`server.js` is a little server that I've put into the dist folder to test the bundle. I'll paste here its source code, please make sure to install `express` and `cors` before running it.

```js
const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();

express.static.mime.define({'application/wasm': ['wasm']});

const port = process.env.PORT || 3000;

app.use(cors({
	origin: process.env.CORS_ALLOW_ORIGIN || '*',
	methods: ['GET', 'PUT', 'POST', 'DELETE', 'OPTIONS'],
	allowedHeaders: ['Content-Type', 'Authorization']
}));

app.use(express.static(path.resolve(__dirname, './')));

app.listen(port, () => {
  console.log('Server active on port: ', port);
});
```

**Comment by LucasMW** [comment] 2018-10-26 20:50
Hi @mbasso,
thank you for your assistance. You answered very quickly and that is appreciated.
With your server.js file I was able to run the built files on dist.
My ignorance about these technologies might be getting in the way, but shouldn't the this server.js also be considered boilerplate code and therefore be generated together inside dist/ folder?
I'm sorry if my question stupid in any way.

**Comment by mbasso** [comment] 2018-10-27 09:16
> thank you for your assistance. You answered very quickly and that is appreciated.

You're welcome 😄

> My ignorance about these technologies might be getting in the way, but shouldn't the this server.js also be considered boilerplate code and therefore be generated together inside dist/ folder?
I'm sorry if my question stupid in any way.

Don't worry, no question is stupid, no one has a complete knowledge of all technologies 😄.
We might include `server.js` into the `dist` folder but, usually, if you run `make` to create the production build is because you want to push it on the cloud or on a remote server that uses node, apache, IIS, nginx or something like that to serve the website. I've created it only to run a little node server to test the build on my local machine. Server configuration might be a lot more complex, so I think that this has to be done by the user and the boilerplate should provide only a way to develop and build the frontend.
What do you think about it?

**Comment by mbasso** [comment] 2018-11-08 08:54
I'll close this issue. Please open another one if necessary 😄

**Closed as completed by mbasso** 2018-11-08 08:54 UTC
